tobiasschuerg/InfluxDB-Client-for-Arduino

- InfluxDb.cpp
- InfluxDb.h
- README.md
- example/Writing_Single_with_Auth/Writing_Single_with_Auth.ino
Added `setDbAuth` to connect with databases that require authentication. Closes #3
> InfluxDb authentication support

- InfluxData.h
I added a method to use a string as the value for the infuxdb write string:
`addValueString`
> added method for Strings as values

- InfluxDb.cpp
- InfluxDb.h
Making code to work over HTTPS connection.
Server's fingerprint is required to be specified manually.
Fixed a bug where subsequent writes() gets failed due to missing 'Token' header
> InfluxDB V2 HTTPS cloud access

- InfluxDb.cpp
> missing uint16_t

- src/InfluxDbClient.cpp
> Fixes #33 wrong status code expected on version 1.x

- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- test/server/server.js
- test/test.ino
Added setting of  _User-Agent_ HTTP header, based on the requirement from InfluxData.
This implies adding versioning constant in the [InfluxDbClient.h](src/InfluxDbClient.h).
Enhanced tests to cover InfluxDB 1 specific endpoints and the new feature.
> Feat: Setting User-Agent header

- src/InfluxDbClient.h
fixes https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/issues/43
> fix: compilation warning on fields order in class Point

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- test/test.ino
> fix: fixing line protocol composition when point has no tags (#50)

- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
This gives an ability to skip all the funny games with certificates.
As soon as you don't care much somebody wants to steal your sensors )
> Option to allow insecure connection

- src/InfluxDbClient.cpp
- src/util/helpers.cpp
- src/util/helpers.h
- test/test.ino
Escaping also measurement name
Escaping additional chars
> fix: proper invalid chars escaping

- CHANGELOG.md
- README.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/util/helpers.cpp
- src/util/helpers.h
- test/TestSupport.h
- test/test.ino
Closes #69.
Better timestamp creation
> fix: better default timestamp generating 

- CHANGELOG.md
- src/query/FluxTypes.cpp
- test/server/server.js
- test/test.ino
Fixed InfluxDB boolean type recognizing.
> fix: proper flux boolean data name

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Options.h
- test/server/server.js
- test/test.ino
- Retry on failure logic unification with other InfluxDB clients (exponential retry, max retry count 3, max retry interval)
- Better write buffer memory management
- Refactored tests
> feat: Write logic improvements

- CHANGELOG.md
- src/Point.cpp
Closes #98
More memory efficient point line composition, as suggested in #98
> fix(memory): better string concatenation

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/Options.cpp
- src/Options.h
- src/Point.cpp
- src/Point.h
- test/test.ino
Adding support for default tags.
> feat: default tags

- CHANGELOG.md
- examples/BasicWrite/BasicWrite.ino
- examples/SecureBatchWrite/SecureBatchWrite.ino
- examples/SecureWrite/SecureWrite.ino
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Point.cpp
- src/Point.h
- test/Test.cpp
- test/TestSupport.cpp
- test/test.ino
Added `InfluxDBClient::pointToLineProtocol(const Point& point)` for simple creation of InfluxDB line-protocol string with respect to default tags.
> feat: added InfluxDBClient::pointToLineProtocol function

- README.md
Cleaned up a lot of language to make it more readable.
> Language cleanup

- src/util/helpers.cpp
> Line 140 Fix

- CHANGELOG.md
- src/InfluxData.cpp
- src/InfluxDb.cpp
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Point.cpp
- src/Point.h
- src/query/FluxParser.cpp
- src/util/helpers.cpp
- test/Test.cpp
- test/Test.h
Closes #123
- Fixing many compilation warnings.
- Properly marking deprecated code.
> fix: fixing compilation warnings

- examples/Buckets/Buckets.ino
- src/BucketsClient.cpp
- src/BucketsClient.h
- src/HTTPService.cpp
- src/HTTPService.h
- src/InfluxDb.cpp
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Options.h
- src/Platform.h
- src/Point.h
- src/Version.h
- src/util/helpers.cpp
- src/util/helpers.h
- test/E2ETest.cpp
- test/E2ETest.h
- test/Test.cpp
- test/Test.h
- test/TestBase.cpp
- test/TestBase.h
- test/server/Readme.md
- test/server/server.js
- test/test.ino
- Added Buckets sub-client. A bucket can be:
- looked for
- checked for existence
- created, with optionally specifying retention policy
- deleted
- Refactored HTTP code to shared `HTTPService` for easy reusing..
> Feat: buckets management

- CHANGELOG.md
- README.md
- examples/QueryParams/QueryParams.ino
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/query/FluxParser.cpp
- src/query/FluxParser.h
- src/query/FluxTypes.cpp
- src/query/FluxTypes.h
- src/query/Params.cpp
- src/query/Params.h
- src/util/helpers.cpp
- src/util/helpers.h
- test/Test.cpp
- test/Test.h
- test/server/server.js
Adding Flux query parameters. Works only for InfluxDB cloud now.
> feat: Adding query params

- .github/workflows/platformio.yml
- README.md
- examples/PlatformIO_BasicWrite/platformio.ini
- examples/PlatformIO_BasicWrite/src/main.cpp
- platformio.ini
Added a complete CI workflow for test the two architectures ESP32 and ESP8266 with a CI over PlatformIO on GitHub Workflows (Actions)
In the root directory of the library only type:
```bash
pio run
``` 
It is only for local tests, after the merge of this PR, Github workflow will doing that alone for you :D
The badge only will be works after this PR, but a little preview is possible in my project [CanAirIO](https://github.com/kike-canaries/canairio_firmware)
> Ci test unit
