- InfluxDb.h
This PS makes it possible to compile and use this library with the ESP32.
Solves part of the #5 but does not add the TLS support.
> ESP32 support

- InfluxData.h
Usecase:
- wake ESP every 5 minutes from deepSleep to make a measurement and store it locally.
- send all the data every 30 minutes to InfluxDB with correct timestamps of previous measurements.
https://docs.influxdata.com/influxdb/v1.7/tools/api/#example-1-write-a-point-to-the-database-mydb-with-a-nanosecond-timestamp
Works for me with a time_t as argument.
```
configTime(0, 0, "pool.ntp.org");
time_t now = time(nullptr);
```
(I'm calculating previous timestamps with "now" & "sleepTimeDuration" to avoid wifi in all the runs that get stored locally and only establish a connection in a run that also writes to the database; the small change in the code works for me ;-)
> Add "setTime" function

- InfluxDb.cpp
I'd been experiencing hangs when using this library on an ESP32 + InfluxDB 1.7.9. I would write measurements and find they would never return.
I'm not attached to the approach, feel free to let me know if there's anything you'd like to change before merging.
> Change to avoid attempting to read an Empty HTTP response on ESP32

- InfluxData.h
I found the default number of decimals in String() is two, which was insufficient for my code (it meant an accuracy of 10W instead of 1W for my electricity metering)
> Add the ability to specify decimal places for float values

- CHANGELOG.md
- src/InfluxDbClient.cpp
- test/server/server.js
- test/test.ino
Although write protocol is the same for both InflluxDB v1 and  v2, there is an incompatibility in precision constant for microseconds used in the write URL, `u` for v1 vs. `us` for v2. 
Unfortunately,  due to the InfluxDB v1 issue [#17622](https://github.com/influxdata/influxdb/issues/17622), the wrong precision constant is not reported back.
This fix creates a workaround for that. Fixes #49
> fix: Fixing microsecond precision constant for v1 (#49)

- CHANGELOG.md
- src/InfluxDbClient.cpp
Closes #54.
Verified on two D1 minis and an ESP32 Dev Kit V1. Quite weird it worked correctly before.
> fix: Correct pointer type for UserAgent string (#54)

- src/InfluxDbClient.h
The lastRetryAfter was not initialized, leading to a possible false-negative about retrying too soon (first if statement in InfluxDBClient::flushBuffer() )
> Properly initialize member variable

- CHANGELOG.md
- README.md
- src/InfluxDbClient.cpp
**ESP8266 only** - Added Max Fragment Length Negotiation for TLS communicaton to reduce memory allocation. If server supports MFLN, it saves ~15kB. Standalone InfluxDB OSS server doesn't support MFLN, Cloud yes. To leverage MFLN for standalone OSS, a reverse proxy must be used.
> feat(ESP8266): Add Max Fragment Length Negotiation for TLS connection

- CHANGELOG.md
- README.md
- examples/SecureBatchWrite/SecureBatchWrite.ino
- src/InfluxDb.cpp
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Options.h
- src/Point.cpp
- src/Point.h
- src/WritePrecision.h
- test/server/server.js
- test/test.ino
Improved API for settings of write and HTTP options:
- Introduced `WriteOptions` to wrap the write related options (write precision, batch-size, etc). It offers fluent style API allowing to change only the required options. `InfluxDBClient` has overloaded `setWriteOptions(const WriteOptions& writeOptions)` method.
- Introduced `HTTPOptions` to wrap the HTTP related options (e.g. reusing connection). It offers fluent style API allowing to change only the required options. `InfluxDBClient` has `setHTTPOptions(const HTTPOptions& httpOptions)` method.
- Added possibility to set HTTP response read timeout (part of the `HTTPOptions`).
- Method `InfluxDBClient::void setWriteOptions(WritePrecision precision, uint16_t batchSize = 1, uint16_t bufferSize = 5, uint16_t flushInterval = 60, bool …
> feat: Refactored options and added HTTP read timeout

- README.md
- examples/BasicWrite/BasicWrite.ino
- examples/QueryAggregated/QueryAggregated.ino
- examples/QueryTable/QueryTable.ino
- src/InfluxDbClient.h
Closes #92 
An example port for InfluxDB 2 changed from 9999 to 8086. Some parts have been rephrased.
Also fixing misleading comment about empty org for v1 forward compatibility API
> feat: changing default v2 port 9999->8086

- src/query/FluxParser.cpp
Closes #
Comment out/remove line 204 in FluxParser - unused declaration
> commented out unused decalaration

- CHANGELOG.md
- src/Point.h
- test/server/server.js
- test/test.ino
Closes #105
Added optional parameter for specifying decimal places of double: `void Point::addField(String name, double value, int decimalPlaces = 2)`
> fix: allowing custom decimal places also for double

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/util/debug.h
- test/test.ino
Closes #96
- Added `canSendRequest()` function to check if retry strategy is applied
- Added `getRemaingRetryTime()` function to get wait time before another request (write/query) can be sent
- Removed applying retry wait time in case of network error
- Better explanatory error message when a request is about to be sent in the retry wait state
> feat: retry strategy improvements

- CHANGELOG.md
- src/InfluxDbClient.cpp
- test/test.ino
Closes #110 
Fixed blocked write after max retry count reached.
Removed max retry count limit on networks errors
> fix: fixed blocked write after max retry count reached

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
Fixing typo in method name:  renamed `InfluxDBClient::getRemaingRetryTime()`->`InfluxDBClient::getRemainingRetryTime()`
> fix: typo in menthod name: getRemaingRetryTime()->getRemainingRetryTime()

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/util/helpers.cpp
- src/util/helpers.h
- test/Test.cpp
- test/Test.h
- test/server/server.js
Closes #116
Added escaping of URL params (org, bucker, V1 username and pass)
> fix: Adding encoding URL params

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- test/Test.cpp
- test/Test.h
- test/TestSupport.cpp
- test/test.ino
Added proper cleaning of WiFiClient instance.
Added other PRs to the changelog
> fix: leaking WiFiClient instance when repeated setting of connection params

- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
Add user and password to the validation ping in validateConnection().
This is needed when "ping-auth-enabled" is set to true in influxdb 1.x.
When "ping-auth-enabled" is set to false the validation succeedes even when user and password are set.
> feat: add user and password to validation ping

- CHANGELOG.md
- README.md
- examples/BasicWrite/BasicWrite.ino
- examples/QueryAggregated/QueryAggregated.ino
- examples/QueryTable/QueryTable.ino
- examples/SecureBatchWrite/SecureBatchWrite.ino
- examples/SecureWrite/SecureWrite.ino
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
Closes #131
- Added untrusted connection (skipping certificate validation) info to Readme
- `SecureWrite` and `SecureBatchWrite` demos enhanced with example about using untrusted connection
- Various fixes of typos
> fix: secure doc, demos

- CHANGELOG.md
- src/query/FluxParser.cpp
- test/server/server.js
Closes #136
Skipping unexpected rows.
- [x ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
> fix: Skipping unexpected annonations (#136)

- CHANGELOG.md
- README.md
- examples/SecureBatchWrite/SecureBatchWrite.ino
- examples/SecureWrite/SecureWrite.ino
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
Closes #141 
Adding call to WifiClientSecure::setInsesure() also for ESP32.
> feat: setInsecure also for ESP32

- CHANGELOG.md
- src/InfluxDbClient.cpp
Closes #149
ESP32 only: Setting `httpReadTimeout` also for `connectTimeout` of `HTTPClient`.
> fix: setting httpReadTimeout as connect timeout for HTTP connection for ESP32

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Point.h
- src/query/HttpStreamScanner.cpp
- src/util/helpers.cpp
- src/util/helpers.h
- test/Test.cpp
- test/Test.h
Closes #160, closes #161
Fixed flushing of buffer when flush interval timeout occurred
- for the first time
- when buffer was not full
> fix: flushing not full buffer when timeout occurs for the first time

- CHANGELOG.md
- README.md
Closes #135
More precise description of supported devices.
> docs: more precise description of supported devices

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- test/Test.cpp
- test/Test.h
- Added possibility to disable retrying by setting `maxRetryAttempts` to zero: `client.setWriteOptions(WriteOptions().maxRetryAttempts(0));` 
- Added `InfluxDBClient::writeRecord(const char *record)`.
> feat: disabling retrying, added writeRecord(const char *record)

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/query/FluxTypes.cpp
- src/query/Params.cpp
> fix: cleared compiler warnings

- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
Continuation of #174. Included constructors and setConnectionParam
> fix: add strings by ref also for constructors and params

- CHANGELOG.md
- src/HTTPService.h
- src/InfluxDbClient.h
Added diagnostic connection state getter `bool InfluxDBClient::isConnected()`.  
Useful when setting connection reuse to `true`.
> feat: adding isConnected to test connection persistence state

- CHANGELOG.md
- README.md
- src/BucketsClient.cpp
- src/HTTPService.cpp
- src/InfluxData.cpp
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Options.cpp
- src/Point.cpp
- src/Point.h
- src/WritePrecision.h
- src/util/debug.h
- src/util/helpers.cpp
- src/util/helpers.h
- test/Test.cpp
- test/Test.h
- test/TestBase.cpp
- test/TestBase.h
- test/test.ino
Closes #168 
Automatically adjusting point timestamp according to the setting of write precision. If no precision is set for client, timestamp is adjusted to nanoseconds by adding zeroes to match the default server precision
> fix: timestamp

- CHANGELOG.md
- src/InfluxData.cpp
- src/InfluxData.h
- src/InfluxDbClient.cpp
- src/Point.cpp
- src/Point.h
- test/Test.cpp
- test/Test.h
- test/TestSupport.cpp
- test/TestSupport.h
- test/test.ino
Closes #197 
Added effective passing Point by value
> fix: Added effective passing Point by value 

- CHANGELOG.md
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- test/Test.cpp
Closes #196 
Removing the strict _override_ keyword to avoid compilation errors on older cores.
> fix: backward compatible compilation of Stream API

- CHANGELOG.md
- README.md
- platformio.ini
- src/InfluxDbClient.cpp
- src/InfluxDbClient.h
- src/Options.h
- src/Point.cpp
- src/Point.h
- test/Test.cpp
- test/Test.h
- test/server/server.js
Closes #201 
Added `WriteOption::useServerTimestamptrue)` to specify timestamp precision and do not send timestamp.
> Feat precision only

- CHANGELOG.md
- src/HTTPService.cpp
- src/HTTPService.h
- src/InfluxDbClient.cpp
- src/Options.cpp
- src/Options.h
- test/Test.cpp
- test/Test.h
- test/test.ino
Closes #206
- Fixed lazy initialization to be done in a connection function
- Fixed typos in test names
> fix: allow setting of options without connection params

- CHANGELOG.md
- src/HTTPService.h
Closes #226 
Added explicit includes which were part of `HTTPClient.h` in ESP32 core 2.x.x
> fix: ESP32 Core 3 compatibility
